#!/usr/bin/env python
#
# bbbm1 - A background manager for Blackbox
# Copyright (C) 2004 Rob Spoor
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.
#

import sys, os, getopt
from string import split, strip, lstrip
from os.path import exists, expanduser, splitext, dirname
from random import choice
from ConfigParser import ConfigParser, NoOptionError
import gtk, GdkImlib, GDK

version = "0.1";
extensions = [".jpg", ".jpeg", ".gif", ".ppm", ".pgm"]
homedir = expanduser("~/.bbbm")
config = homedir + os.sep + "bbbm.cfg"
thumbsdir = homedir + os.sep + "thumbs"

set_command, view_command, thumb_size, thumb_cols = None, None, None, 0

def read_options():
    global config, set_command, view_command, thumb_size, thumb_cols
    try:
        f = open(config, "r")
        lines = f.readlines()
        f.close()
    except IOError:
        sys.stderr.write("Error: could not read '" + config + "'\n")
        sys.exit(1)
    for i in range(len(lines)):
        line = lstrip(lines[i][:-1])
        if not line or line[0] == "#":
            continue
        try:
            option, value = split(line, " = ", 1)
        except ValueError:
            sys.stderr.write("Error on line " + (i + 1) + ": " + line + "\n")
            sys.exit(1)
        if option == "set_command":
            set_command = value
        elif option == "view_command":
            view_command = value
        elif option == "thumb_size":
            thumb_size = value
        elif option == "thumb_cols":
            try:
                thumb_cols = int(value)
            except ValueError:
                sys.stderr.write("Illegal value of 'thumb_cols': " + value +\
                                 "\n")
                sys.exit(1)
    if not set_command:
        sys.stderr.write("Error: option 'set_command' missing\n")
        sys.exit(1)
    if not view_command:
        sys.stderr.write("Error: option 'view_command' missing\n")
        sys.exit(1)
    if not thumb_size:
        sys.stderr.write("Error: option 'thumb_size' missing\n")
        sys.exit(1)
    if not thumb_cols:
        sys.stderr.write("Error: option 'thumb_cols' missing or 0\n")
        sys.exit(1)
    if thumb_cols > 10:
        thumb_cols = 10

def write_options():
    global config, set_command, view_command, thumb_size, thumb_cols
    try:
        f = open(config, "w")
    except IOError:
        sys.stderr.write("Error: could not write to '" + config + "'\n")
        return
    # don't quit!
    f.write("# Warning: editing this file is not recommended.\n")
    f.write("# This file will be overwritten when bbbm1 closes.\n\n")
    f.write("set_command = " + set_command + "\n")
    f.write("view_command = " + view_command + "\n")
    f.write("thumb_size = " + thumb_size + "\n")
    f.write("thumb_cols = " + str(thumb_cols) + "\n")
    f.close()

# Info image included here because it's not a stock item as in GTK2.
# Also, I want everything in just one file.
info_img = [
"48 48 598 2",
"  	c None",
". 	c #525255",
"+ 	c #9A9AA0",
"@ 	c #BDBDC6",
"# 	c #D6D6E0",
"$ 	c #E1E1EE",
"% 	c #E4E4F2",
"& 	c #DFDFED",
"* 	c #D0D0DD",
"= 	c #B3B3BF",
"- 	c #86868F",
"; 	c #3B3B3E",
"> 	c #6D6D70",
", 	c #C1C1C7",
"' 	c #EAEAF5",
") 	c #EAEAF4",
"! 	c #E8E8F3",
"~ 	c #E6E6F3",
"{ 	c #E3E3F1",
"] 	c #E2E2F1",
"^ 	c #DFDFF0",
"/ 	c #DEDEEF",
"( 	c #ADADB9",
"_ 	c #4B4B4F",
": 	c #000000",
"< 	c #AFAFB5",
"[ 	c #EDEDF6",
"} 	c #F0F0F7",
"| 	c #F1F1F8",
"1 	c #EFEFF7",
"2 	c #EBEBF5",
"3 	c #E0E0F1",
"4 	c #DEDEF0",
"5 	c #DDDDEF",
"6 	c #DCDDEF",
"7 	c #9595A0",
"8 	c #4F4F51",
"9 	c #D4D4DA",
"0 	c #F3F3F8",
"a 	c #F6F6FA",
"b 	c #F8F8FB",
"c 	c #F7F7FB",
"d 	c #F5F5FA",
"e 	c #E9E9F4",
"f 	c #E5E5F3",
"g 	c #E1E1F1",
"h 	c #DEDFF0",
"i 	c #DCDCEF",
"j 	c #DBDCEF",
"k 	c #BDBECD",
"l 	c #262629",
"m 	c #505052",
"n 	c #DEDEE5",
"o 	c #F4F4F9",
"p 	c #F9F9FC",
"q 	c #FBFBFD",
"r 	c #ECECF5",
"s 	c #E4E4F3",
"t 	c #DFE0F0",
"u 	c #DCDEF0",
"v 	c #DBDCEE",
"w 	c #DBDBEF",
"x 	c #DADBEE",
"y 	c #C7C8D9",
"z 	c #252528",
"A 	c #D5D5DB",
"B 	c #F1F1F9",
"C 	c #FCFCFD",
"D 	c #FDFDFE",
"E 	c #F8F8FC",
"F 	c #F3F3F9",
"G 	c #EEEEF7",
"H 	c #E7E8F4",
"I 	c #E2E3F2",
"J 	c #DFE0F1",
"K 	c #DDDFF0",
"L 	c #DADDEF",
"M 	c #DADCEE",
"N 	c #D9DBEE",
"O 	c #BDBFCF",
"P 	c #B3B3B8",
"Q 	c #F2F2F9",
"R 	c #E8E8F4",
"S 	c #E5E6F3",
"T 	c #E3E3F3",
"U 	c #E0E1F1",
"V 	c #DDDEF0",
"W 	c #DBDDEF",
"X 	c #D8DBEE",
"Y 	c #9496A2",
"Z 	c #737375",
"` 	c #FAFAFC",
" .	c #E9E9F5",
"..	c #E3E4F3",
"+.	c #E1E1F2",
"@.	c #DBDDF0",
"#.	c #D9DCEE",
"$.	c #D8DAEE",
"%.	c #D7DAEE",
"&.	c #3B3C41",
"*.	c #C5C5CA",
"=.	c #FBFBFC",
"-.	c #F9F9FB",
";.	c #F0F0F8",
">.	c #ECECF6",
",.	c #E7E7F4",
"'.	c #E1E2F2",
").	c #D8DCEE",
"!.	c #D7DBED",
"~.	c #D6DAED",
"{.	c #D6DBEE",
"].	c #A8AAB8",
"^.	c #5B5B5D",
"/.	c #F2F2F8",
"(.	c #EDEEF7",
"_.	c #EBEBF6",
":.	c #E6E6F4",
"<.	c #D7DBEC",
"[.	c #D6DBEC",
"}.	c #D6DAEC",
"|.	c #D6DAEE",
"1.	c #D6D9EE",
"2.	c #202124",
"3.	c #A3A3A7",
"4.	c #FFFFFF",
"5.	c #F3F4F9",
"6.	c #EFEFF8",
"7.	c #EBECF6",
"8.	c #E5E6F4",
"9.	c #E1E3F2",
"0.	c #DDDFEF",
"a.	c #D8DCED",
"b.	c #D7DCEC",
"c.	c #D6DCEC",
"d.	c #D5DBED",
"e.	c #D5DAEE",
"f.	c #73757F",
"g.	c #C7C7CD",
"h.	c #F4F4FA",
"i.	c #ECECF7",
"j.	c #E9EAF5",
"k.	c #E5E5F4",
"l.	c #DEE2F0",
"m.	c #DADEEE",
"n.	c #D7DEEC",
"o.	c #D5DBEC",
"p.	c #D5DCED",
"q.	c #D5DBEE",
"r.	c #A7AAB9",
"s.	c #FAFAFB",
"t.	c #E8E9F5",
"u.	c #E1E4F2",
"v.	c #DBE0EF",
"w.	c #D8DFED",
"x.	c #D5DDEB",
"y.	c #D5DCEC",
"z.	c #C3C6D9",
"A.	c #EAEAF3",
"B.	c #F6F6FB",
"C.	c #F5F5FB",
"D.	c #EFF0F8",
"E.	c #EAEBF6",
"F.	c #E4E6F3",
"G.	c #DDE1EF",
"H.	c #D9E0ED",
"I.	c #D6DFEB",
"J.	c #D4DCEC",
"K.	c #D4DAEE",
"L.	c #D0D3E9",
"M.	c #FEFEFE",
"N.	c #F2F3FA",
"O.	c #F0F1F8",
"P.	c #E5E7F4",
"Q.	c #DEE2EF",
"R.	c #D9E1EE",
"S.	c #D6E1EB",
"T.	c #D4DEEB",
"U.	c #D4DDEC",
"V.	c #D4D8EE",
"W.	c #E8E8F1",
"X.	c #EEEEF6",
"Y.	c #F5F5F9",
"Z.	c #F7F7FA",
"`.	c #FDFDFD",
" +	c #E9E7E6",
".+	c #DFE4F0",
"++	c #D9E3EC",
"@+	c #D6E2EA",
"#+	c #D4E0EA",
"$+	c #D4DEEC",
"%+	c #D4DAED",
"&+	c #D0D4E9",
"*+	c #D9D9E2",
"=+	c #F1F1F7",
"-+	c #EFEDE8",
";+	c #F2F3F9",
">+	c #EAEAF0",
",+	c #E3E7F2",
"'+	c #DEE5EF",
")+	c #D8E4EB",
"!+	c #D5E4EA",
"~+	c #D4E3EA",
"{+	c #D3DFEB",
"]+	c #D4DCED",
"^+	c #C3C9DA",
"/+	c #BFBFC6",
"(+	c #F3F3F5",
"_+	c #EDEBE7",
":+	c #F5F6FA",
"<+	c #F1F2F9",
"[+	c #E8E6E5",
"}+	c #EAECF5",
"|+	c #E6E7F3",
"1+	c #E0E4EF",
"2+	c #DCE5EC",
"3+	c #D7E7EA",
"4+	c #D5E7EA",
"5+	c #D4E5EA",
"6+	c #D3E0EB",
"7+	c #D3DDED",
"8+	c #A8ADBC",
"9+	c #94949A",
"0+	c #EAEBF4",
"a+	c #ECEDF4",
"b+	c #EEEFF6",
"c+	c #F1F2F8",
"d+	c #F2F3F8",
"e+	c #D1D0D1",
"f+	c #EFF0F7",
"g+	c #EEEFF7",
"h+	c #ECEDF6",
"i+	c #E2E0DF",
"j+	c #E5E8F3",
"k+	c #E2E6F1",
"l+	c #DDE4ED",
"m+	c #DAE6EB",
"n+	c #D6E7EA",
"o+	c #D5E9E9",
"p+	c #D3E7EA",
"q+	c #D3DDEC",
"r+	c #747780",
"s+	c #49494B",
"t+	c #E5E8F0",
"u+	c #E8EBF2",
"v+	c #E9ECF2",
"w+	c #EAEDF4",
"x+	c #EBEDF4",
"y+	c #EDEEF5",
"z+	c #C3C3C4",
"A+	c #EDEFF6",
"B+	c #EDEEF6",
"C+	c #EBEDF5",
"D+	c #E9EBF5",
"E+	c #DADAD7",
"F+	c #E0E4EE",
"G+	c #DCE4EC",
"H+	c #DAE5EB",
"I+	c #D4E9E9",
"J+	c #D3EAE9",
"K+	c #D3E0EC",
"L+	c #D2DCED",
"M+	c #202023",
"N+	c #B8B8C1",
"O+	c #E6E6F2",
"P+	c #E3E7EF",
"Q+	c #E3EBEF",
"R+	c #E4EBF0",
"S+	c #E6ECF1",
"T+	c #E6EAF1",
"U+	c #E6EBF2",
"V+	c #E2E4E4",
"W+	c #E7EBF3",
"X+	c #E7EAF3",
"Y+	c #E6EAF3",
"Z+	c #E5E9F3",
"`+	c #E4E7F3",
" @	c #E2E7F0",
".@	c #A4A7AD",
"+@	c #DCE2EC",
"@@	c #D9E4EA",
"#@	c #D7E6EA",
"$@	c #D5EAE9",
"%@	c #D4EBE9",
"&@	c #D3ECE9",
"*@	c #D3E3EA",
"=@	c #D2DEEC",
"-@	c #A8ADBB",
";@	c #5A5A5E",
">@	c #E4E5F1",
",@	c #E4E6F2",
"'@	c #E1E8EE",
")@	c #E0EAED",
"!@	c #E1EAEE",
"~@	c #E1E9EE",
"{@	c #E1E9F0",
"]@	c #E3EAEF",
"^@	c #D3D5CB",
"/@	c #E1E8F1",
"(@	c #E1E7F0",
"_@	c #E0E6F0",
":@	c #DEE5F0",
"<@	c #DDE4F0",
"[@	c #DBE2EF",
"}@	c #DEE4ED",
"|@	c #9FA5A5",
"1@	c #D7E2E9",
"2@	c #D6E5E9",
"3@	c #D4E9E8",
"4@	c #D4EDE9",
"5@	c #D3EEE9",
"6@	c #D3E7E9",
"7@	c #D3E1EC",
"8@	c #38383E",
"9@	c #A2A4AC",
"0@	c #E3E4F1",
"a@	c #E3E5F1",
"b@	c #DEE8EC",
"c@	c #DEEAEC",
"d@	c #DDE9EC",
"e@	c #DCE8EB",
"f@	c #DEE8EB",
"g@	c #A4ACA9",
"h@	c #DAE5EC",
"i@	c #DAE4EC",
"j@	c #D9E2EC",
"k@	c #D8E1EA",
"l@	c #D8DFEA",
"m@	c #D7DFEA",
"n@	c #CACCC2",
"o@	c #CDD1CA",
"p@	c #D5E2E8",
"q@	c #D4E7E9",
"r@	c #D3E1EB",
"s@	c #D2DDEC",
"t@	c #9296A2",
"u@	c #C8CAD5",
"v@	c #E1E3F0",
"w@	c #DCE3EA",
"x@	c #DBE7EB",
"y@	c #DAE7EA",
"z@	c #DAE8EB",
"A@	c #A0AAA6",
"B@	c #D8E3EA",
"C@	c #D7E1E9",
"D@	c #D6DFE9",
"E@	c #D6DEE8",
"F@	c #DAE2E8",
"G@	c #C9CEC0",
"H@	c #D5E2E9",
"I@	c #D5E6E9",
"J@	c #D4EAE9",
"K@	c #D3E2EA",
"L@	c #D3DFEC",
"M@	c #BAC1D1",
"N@	c #2E2E31",
"O@	c #CFD0DE",
"P@	c #DEE0F0",
"Q@	c #DBE2EA",
"R@	c #DAE5EA",
"S@	c #DAE4EA",
"T@	c #C9CFC1",
"U@	c #CDD4CA",
"V@	c #D8E2EA",
"W@	c #D7E3E9",
"X@	c #D6E1E9",
"Y@	c #DCE7E9",
"Z@	c #949F9B",
"`@	c #D5E5E9",
" #	c #D3E8E9",
".#	c #D2DFEC",
"+#	c #C5CCDC",
"@#	c #1D1D20",
"##	c #2A2A2E",
"$#	c #C2C3D0",
"%#	c #DCDEEE",
"&#	c #DCDDEE",
"*#	c #D8DCE9",
"=#	c #D8DFE8",
"-#	c #D4DDE4",
";#	c #9FA7A2",
">#	c #D0D8D3",
",#	c #CFD6D1",
"'#	c #CFD6CF",
")#	c #D1D8CF",
"!#	c #DCE8E8",
"~#	c #949E9B",
"{#	c #D4E2E3",
"]#	c #D3E3E7",
"^#	c #D3E0E7",
"/#	c #D2DEE8",
"(#	c #BBC3D2",
"_#	c #1D1D1F",
":#	c #9999A4",
"<#	c #D3D4E5",
"[#	c #BDBABB",
"}#	c #B8B7B5",
"|#	c #C3C0B4",
"1#	c #BEBFB7",
"2#	c #C2C4B8",
"3#	c #C8C9B7",
"4#	c #CECEB9",
"5#	c #D0CFB9",
"6#	c #C6C5B3",
"7#	c #CBCAB6",
"8#	c #CCCFCA",
"9#	c #CFD7DB",
"0#	c #D3DEEC",
"a#	c #969BA6",
"b#	c #3D3D42",
"c#	c #CBC1AB",
"d#	c #BAB6B8",
"e#	c #B4B4B6",
"f#	c #B6B4B6",
"g#	c #BDBBBB",
"h#	c #C0BEBB",
"i#	c #C7C3BB",
"j#	c #CEC9BC",
"k#	c #CFCABC",
"l#	c #CDCABB",
"m#	c #CAC8BA",
"n#	c #C8C6B9",
"o#	c #B5B197",
"p#	c #35383C",
"q#	c #ECE3C4",
"r#	c #D3C8A8",
"s#	c #CDC4A7",
"t#	c #CDC8BB",
"u#	c #CDCAC4",
"v#	c #C8C5C2",
"w#	c #C9C6C1",
"x#	c #CCC7B9",
"y#	c #CFC7B2",
"z#	c #CDC3A4",
"A#	c #D5CCAF",
"B#	c #D2C69D",
"C#	c #9C8C53",
"D#	c #F1DF9D",
"E#	c #F2E9C5",
"F#	c #F8F4E7",
"G#	c #F9F7EF",
"H#	c #F7F4EB",
"I#	c #EEE8D2",
"J#	c #EDE6CE",
"K#	c #F0EAD2",
"L#	c #F2ECD4",
"M#	c #E6DCB7",
"N#	c #DBCE9E",
"O#	c #BEAB66",
"P#	c #6F643A",
"Q#	c #F3E3AA",
"R#	c #E6D79F",
"S#	c #F3E3A8",
"T#	c #F3E4AD",
"U#	c #F0DE9C",
"V#	c #E9D488",
"W#	c #E0CB7B",
"X#	c #D9C374",
"Y#	c #D0BB6F",
"Z#	c #C7B36B",
"`#	c #A9985A",
" $	c #8D7F4B",
".$	c #F8F3E1",
"+$	c #F8F0D5",
"@$	c #E6D69F",
"#$	c #D6C896",
"$$	c #D0C292",
"%$	c #CEBE86",
"&$	c #C5B474",
"*$	c #C2AF6A",
"=$	c #BBA864",
"-$	c #BFB07B",
";$	c #C5BA8F",
">$	c #CFC08E",
",$	c #9E8E54",
"'$	c #F0DC96",
")$	c #F6EBC5",
"!$	c #FBF8EE",
"~$	c #FCFBF5",
"{$	c #FDFBF6",
"]$	c #F9F4DE",
"^$	c #F3EAC7",
"/$	c #F1E6C1",
"($	c #ECE2BE",
"_$	c #EBE2C1",
":$	c #DFD4AD",
"<$	c #BDAA64",
"[$	c #887C52",
"}$	c #F3E6B6",
"|$	c #E3D296",
"1$	c #F1E1A8",
"2$	c #F4E7B9",
"3$	c #F2E4B1",
"4$	c #EFDD9C",
"5$	c #E7D288",
"6$	c #DFC97A",
"7$	c #CCB76D",
"8$	c #C4B069",
"9$	c #A29565",
"0$	c #90855B",
"a$	c #F7EFD6",
"b$	c #F4EAC7",
"c$	c #E6D8AA",
"d$	c #D4C697",
"e$	c #D1C59C",
"f$	c #CEC190",
"g$	c #C4B275",
"h$	c #BDAA67",
"i$	c #B6A361",
"j$	c #AE9D5D",
"k$	c #C8BD9A",
"l$	c #D1C599",
"m$	c #998B52",
"n$	c #EBD792",
"o$	c #F1E5BA",
"p$	c #F9F5E6",
"q$	c #FCFAF4",
"r$	c #FBF9EE",
"s$	c #F9F6EA",
"t$	c #F5EED7",
"u$	c #ECE3C0",
"v$	c #EADFBC",
"w$	c #E8E0C3",
"x$	c #D2C492",
"y$	c #B8A462",
"z$	c #837646",
"A$	c #F0E6BE",
"B$	c #DFD099",
"C$	c #EDE0B1",
"D$	c #EEE2B3",
"E$	c #EBDCA7",
"F$	c #E6D597",
"G$	c #DDC982",
"H$	c #D3BF72",
"I$	c #CDB86D",
"J$	c #C9B46A",
"K$	c #BCAA65",
"L$	c #9F8F55",
"M$	c #72673C",
"N$	c #F6F1DE",
"O$	c #F1E9CB",
"P$	c #E6DCB9",
"Q$	c #D4C9A3",
"R$	c #CCC19A",
"S$	c #C3B480",
"T$	c #B9A86C",
"U$	c #B2A060",
"V$	c #AC9B5C",
"W$	c #A59558",
"X$	c #BFB38B",
"Y$	c #CCBF92",
"Z$	c #92824E",
"`$	c #897F58",
" %	c #E4D39B",
".%	c #F1EACE",
"+%	c #F8F6EB",
"@%	c #F8F5E9",
"#%	c #EFE7CC",
"$%	c #EBE2C2",
"%%	c #E7DEBC",
"&%	c #E7DEC1",
"*%	c #D9D0A9",
"=%	c #C4B57F",
"-%	c #A19056",
";%	c #13110A",
">%	c #29271E",
",%	c #D1C185",
"'%	c #E0D198",
")%	c #E0D2A0",
"!%	c #E0D19D",
"~%	c #DAC98F",
"{%	c #D0BC7A",
"]%	c #C7B46C",
"^%	c #C3B068",
"/%	c #BEAA66",
"(%	c #A79759",
"_%	c #3D361F",
":%	c #050402",
"<%	c #030303",
"[%	c #454237",
"}%	c #9E9572",
"|%	c #AEA47F",
"1%	c #AA9E73",
"2%	c #928553",
"3%	c #847847",
"4%	c #6B6242",
"5%	c #35301C",
"6%	c #282415",
"7%	c #020201",
"8%	c #2A2A2A",
"9%	c #838383",
"0%	c #767676",
"a%	c #242424",
"b%	c #191919",
"c%	c #161616",
"d%	c #626262",
"e%	c #707070",
"f%	c #1F1F1F",
"g%	c #050505",
"                                                                                                ",
"                                                                                                ",
"                                  . + @ # $ % & * = - ;                                         ",
"                              > , ' ' ) ' ! ~ % { ] ^ / ( _ :                                   ",
"                            < [ } | | } 1 2 ! ~ % { 3 4 5 6 7 :                                 ",
"                        8 9 1 0 a b c d } 2 e ! f % g h 6 i j k l                               ",
"                      m n | o p q q b o 1 r ' e ~ s ] t u v w x y z                             ",
"                      A B d p C D C E F 1 G r ' H f I J K L M N N O :                           ",
"                    P Q F b q C C q c Q | 1 [ ' R S T U V W M X N X Y :                         ",
"                  Z B F a ` q q q ` a F B } G 2  .~ ..+.h @.#.X $.X %.&.                        ",
"                  *.F d b p ` =.` -.c d F ;.G >.' ,.f '.h @.).!.!.~.{.].:                       ",
"                ^.| F d c p q C q p c a o /.;.(._. .:.T U u X <.[.}.|.1.2.                      ",
"                3.| F d b ` C 4.C ` -.c d 5./.6.G 7. .8.9.0.a.b.c.[.d.e.f.:                     ",
"                g.| F d c p q C q ` p b c d h.Q | 6.i.j.k.l.m.n.c.o.p.q.r.:                     ",
"                n | F d c b ` =.q s.-.b c a d 5.Q | 1 >.t.u.v.w.x.x.y.e.z.:                     ",
"                A.} B F d b b s.` ` -.-.E b c B.C.F Q D.E.F.G.H.I.x.J.K.L.:                     ",
"                [ 1 | Q o c b b -.-.-.M.M.p 4.c 4.F N.O.i.P.Q.R.S.T.U.K.V.:                     ",
"                W.G X.| Q Y.a Z.`.`.`.b `.Z.`.a `.`./. +_.P..+++@+#+$+%+&+:                     ",
"                *+r G 1 =+o d a -+Z.Z.M.c 4.c 4.o ;+/.>+E.,+'+)+!+~+{+]+^+:                     ",
"                /+' r [ 1 | /.Y.(+_+:+d Y.o F F <+O.[+}+|+1+2+3+4+5+6+7+8+:                     ",
"                9+e ) 0+a+b+} c+d+e+0 ;+/.| O.f+g+h+i+j+k+l+m+n+o+p+6+q+r+:                     ",
"                s+|+! t+u+v+w+x+y+z+b+A+B+h+C+}+D+0+E+F+G+H+3+I+J+p+K+L+M+                      ",
"                  N+O+P+Q+R+S+T+U+V+W+W+X+Y+Z+`+k+ @.@+@@@#@$@%@&@*@=@-@:                       ",
"                  ;@>@,@'@)@!@~@{@]@^@/@(@_@:@<@[@}@|@1@2@3@4@5@6@7@L+8@:                       ",
"                    9@0@a@b@c@d@e@f@g@h@i@j@k@l@m@n@o@p@q@%@5@&@r@s@t@:                         ",
"                    : u@v@w@x@y@z@e@A@B@1@C@D@E@F@G@H@I@J@4@&@K@L@M@: :                         ",
"                      N@O@P@P@Q@R@S@T@U@V@W@1@X@Y@Z@`@q@J@ #7@.#+#@#:                           ",
"                        ##$#%#&#*#=#-#;#>#,#'#)#!#~#{#]#^#/#L@(#_#:                             ",
"                          : :#v <#[#}#|#1#2#3#4#5#6#7#8#9#0#a#: :                               ",
"                            : b#c#d#e#f#g#h#i#j#k#l#m#n#o#p#: :                                 ",
"                                q#r#s#t#u#v#w#x#y#z#A#B#C#:                                     ",
"                                D#E#F#G#H#I#J#K#L#M#N#O#P#:                                     ",
"                                Q#R#S#T#Q#U#V#W#X#Y#Z#`# $:                                     ",
"                                .$+$@$#$$$%$&$*$=$-$;$>$,$:                                     ",
"                                '$)$!$~${$]$^$/$($_$:$<$[$:                                     ",
"                                }$|$1$2$3$4$5$6$X#7$8$9$0$:                                     ",
"                                a$b$c$d$e$f$g$h$i$j$k$l$m$:                                     ",
"                                n$o$p$q$r$s$t$u$v$w$x$y$z$:                                     ",
"                                A$B$C$D$E$F$G$H$I$J$K$L$M$:                                     ",
"                                N$O$P$Q$R$S$T$U$V$W$X$Y$Z$:                                     ",
"                                `$ %.%+%@%#%$%%%&%*%=%-%;%:                                     ",
"                                >%,%'%)%!%~%{%]%^%/%(%_%:%                                      ",
"                                  <%[%}%|%1%2%3%4%5%6%7%:                                       ",
"                                      : 8%9%0%a%b%: :                                           ",
"                                        c%d%e%f%g%:                                             ",
"                                          : : : :                                               ",
"                                                                                                ",
"                                                                                                "]

class Image(gtk.GtkEventBox):
    def __init__(self, filename, description, thumb):
        gtk.GtkEventBox.__init__(self)
        image = GdkImlib.Image(thumb)
        image.render()
        pic = image.make_pixmap()
        pic.show()
        self.add(pic)
        self.filename = filename
        self.description = description

class BBBM:
    def __init__(self, files):
        self.padding = 5
        self.images = []
        self.filename = None
        self.window = gtk.GtkWindow(gtk.WINDOW_TOPLEVEL)
        self.window.set_default_size(640, 480)
        self.window.set_title("bbbm1 " + version)
        self.window.set_position(gtk.WIN_POS_CENTER)
        self.window.connect("delete_event", self.exit)

        vbox = gtk.GtkVBox(gtk.FALSE, 0)
        vbox.set_border_width(0)
        self.window.add(vbox)
        vbox.show()

        menu_bar = self.create_bar(self.window)
        vbox.pack_start(menu_bar, gtk.FALSE, gtk.TRUE, 0)
        self.status_bar = gtk.GtkStatusbar()
        self.context_id = self.status_bar.get_context_id("Statusbar")
        vbox.pack_end(self.status_bar, gtk.FALSE, gtk.FALSE, 0)

        self.scroll = gtk.GtkScrolledWindow()
        self.table = gtk.GtkTable(1, 1, gtk.TRUE)
        self.table.show()
        self.scroll.add_with_viewport(self.table)
        vbox.pack_start(self.scroll, gtk.TRUE, gtk.TRUE, 0)
        self.scroll.show()

        menu_bar.show()
        self.status_bar.show()
        self.window.show()
        if files:
            if exists(files[0]):
                self.open_collection(files[0])
            else:
                sys.stderr.write("Error: could not find '" + files[0] + "'\n")

    def create_bar(self, window):
        menu_items = (
            ("/_File", None, None, 0, "<Branch>"),
            ("/File/_Open...", "<ctrl>O", self.open, 0, None),
            ("/File/_Save", "<ctrl>S", self.save, 0, None),
            ("/File/Save _As...", "<ctrl><shift>S", self.save_as, 0, None),
            ("/File/_Close", "<ctrl>C", self.close, 0, None),
            ("/File/sep", None, None, 0, "<Separator>"),
            ("/File/E_xit", "<alt>F4", self.exit, 0, None),
            ("/_Edit", None, None, 0, "<Branch>"),
            ("/Edit/_Add Image...", "<ctrl>A", self.add_image, 0, None),
            ("/Edit/Add _Collection...", "<ctrl><shift>A",\
             self.add_collection, 0, None),
            ("/_Tools", None, None, 0, "<Branch>"),
            ("/Tools/Create _List...", "<ctrl>L", self.create_list, 0, None),
            ("/Tools/Create _Menu...", "<ctrl>M", self.create_menu, 0, None),
            ("/Tools/_Random Background", "<ctrl>R", self.random_background,\
             0, None),
            ("/Tools/sep", None, None, 0, "<Separator>"),
            ("/Tools/_Options...", "<alt>P", self.options, 0, None),
            ("/_Help", None,None, 0, "<Branch>"),
            ("/Help/_About", None, self.about, 0, None)
        )
        accel_grp = gtk.GtkAccelGroup()
        item_factory = gtk.GtkItemFactory(gtk.GtkMenuBar, "<main>", accel_grp)
        item_factory.create_items(menu_items)
        window.add_accel_group(accel_grp)
        return item_factory.get_widget("<main>")

    def open(self, widget, data):
        # sometimes the statusbar does not get cleared; do it manually
        self.clear_status(None, None)
        chooser = gtk.GtkFileSelection("Select a collection")
        chooser.set_transient_for(self.window)
        # center, regardless of where the parent is.
        # This is the best alternative, since IN_POS_CENTER_ON_PARENT does not
        # exists in GTK1
        chooser.set_position(gtk.WIN_POS_CENTER)
        # GTK1 has no support for multiple selections, so no need to set to
        # single selection
        chooser.ok_button.connect("clicked", self.open0, chooser)
        chooser.cancel_button.connect("clicked", self.close_dialog, chooser)
        chooser.show()

    def open0(self, widget, chooser):
        self.open_collection(chooser.get_filename())
        chooser.destroy()

    def open_collection(self, file):
        # opening a new collection is adding a new collection with closing the
        # previous opened collection and setting the filename first
        self.close(None, None)
        self.filename = file
        self.add_col(file)

    def save(self, widget, data):
        if self.filename:
            f = open(self.filename, "w")
            for i in self.images:
                f.write(i.filename + "\n" + i.description + "\n")
            f.close()
        else:
            self.save_as(None, None)

    def save_as(self, widget, data):
        # sometimes the statusbar does not get cleared; do it manually
        self.clear_status(None, None)
        chooser = gtk.GtkFileSelection("Save as")
        chooser.set_transient_for(self.window)
        # center, regardless of where the parent is.
        # This is the best alternative, since IN_POS_CENTER_ON_PARENT does not
        # exists in GTK1
        chooser.set_position(gtk.WIN_POS_CENTER)
        # GTK1 has no support for multiple selections, so no need to set to
        # single selection
        chooser.ok_button.connect("clicked", self.save_collection, chooser)
        chooser.cancel_button.connect("clicked", self.close_dialog, chooser)
        chooser.show()

    def save_collection(self, widget, chooser):
        self.filename = chooser.get_filename()
        self.save(widget, None)
        chooser.destroy()

    def close(self, widget, data):
        for i in self.table.children():
            self.table.remove(i)
        self.images = []
        self.filename = None
        self.status_bar.pop(self.context_id)

    def exit(self, widget, data):
        global config, thumbsdir
        write_options()
        # remove thumbs
        os.system("rm -rf " + thumbsdir + os.sep + "*")
        gtk.mainquit()

    def add_image(self, widget, data):
        # sometimes the statusbar does not get cleared; do it manually
        self.clear_status(None, None)
        chooser = gtk.GtkFileSelection("Select an image")
        chooser.set_transient_for(self.window)
        # center, regardless of where the parent is.
        # This is the best alternative, since IN_POS_CENTER_ON_PARENT does not
        # exists in GTK1
        chooser.set_position(gtk.WIN_POS_CENTER)
        # GTK1 has no support for multiple selections, so just add one at a
        # time; use single selection
        chooser.hide_fileop_buttons()
        chooser.ok_button.connect("clicked", self.add_imgage0, chooser)
        chooser.cancel_button.connect("clicked", self.close_dialog, chooser)
        chooser.show()

    def add_imgage0(self, widget, chooser):
        global extensions
        # GTK1 has no support for multiple selections, so just add one at a
        # time
        file = chooser.get_filename()
        if splitext(file)[1] in extensions:
            self.add_img(file)
        chooser.destroy()

    def add_img(self, filename, description=None):
        global thumbsdir, thumb_size, thumb_cols
        if not description:
            description = filename
        if not exists(thumbsdir):
            os.mkdir(thumbsdir)
        thumb = thumbsdir + os.sep + filename
        if not exists(dirname(thumb)):
            os.makedirs(dirname(thumb))
        cmd = "convert -size " + thumb_size + " -resize " + thumb_size + " " +\
              filename + " " + thumb
        os.system(cmd)
        image = Image(filename, description, thumb)
        # pass image twice; the first time it is recognized as a
        # gtk.GtkEventBox, only the second time as an Image
        image.connect_object("button-press-event", self.set_img, image, image)
        image.connect_object("button-release-event", self.popup, image, image)
        image.connect_object("enter-notify-event", self.set_status, image,\
                             image)
        image.connect_object("leave-notify-event", self.clear_status, image)
        image.show()
        img_num = len(self.images)
        c = img_num % thumb_cols
        r = img_num / thumb_cols
        self.images.append(image)
        self.table.attach(image, c, c + 1, r, r + 1, 0, 0,\
                          self.padding, self.padding)

    def set_status(self, widget, event, image):
        self.status_bar.push(self.context_id, image.description)

    def clear_status(self, widget, event):
        self.status_bar.pop(self.context_id)

    def add_collection(self, widget, data):
        # sometimes the statusbar does not get cleared; do it manually
        self.clear_status(None, None)
        chooser = gtk.GtkFileSelection("Select a collection")
        chooser.set_transient_for(self.window)
        # center, regardless of where the parent is.
        # This is the best alternative, since IN_POS_CENTER_ON_PARENT does not
        # exists in GTK1
        chooser.set_position(gtk.WIN_POS_CENTER)
        # GTK1 has no support for multiple selections, so just add one at a
        # time
        chooser.ok_button.connect("clicked", self.add_collection0, chooser)
        chooser.cancel_button.connect("clicked", self.close_dialog, chooser)
        chooser.show()

    def add_collection0(self, widget, chooser):
        self.add_col(chooser.get_filename())
        chooser.destroy()

    def add_col(self, file):
        global extensions
        self.filename = file
        f = open(self.filename, "r")
        lines = f.readlines()
        f.close()
        while lines:
            try:
                file, desc, lines = strip(lines[0]), strip(lines[1]), lines[2:]
            except IndexError:
                file, lines = strip(lines[0]), lines[1:]
                desc = file
            if exists(file) and splitext(file)[1] in extensions:
                self.add_img(file, desc)

    def options(self, widget, data):
        global set_command, view_command, thumb_size, thumb_cols
        # sometimes the statusbar does not get cleared; do it manually
        self.clear_status(None, None)
        values = []
        dialog = gtk.GtkDialog()
        dialog.set_title("Options")
        dialog.set_transient_for(self.window)
        # center, regardless of where the parent is.
        # This is the best alternative, since IN_POS_CENTER_ON_PARENT does not
        # exists in GTK1
        dialog.set_position(gtk.WIN_POS_CENTER)
        frame = gtk.GtkFrame("Commands")
        table = gtk.GtkTable(2, 2, gtk.TRUE)
        label = gtk.GtkLabel("Set command:")
        label.show()
        table.attach(label, 0, 1, 0, 1)
        entry = gtk.GtkEntry()
        entry.set_text(set_command)
        entry.show()
        table.attach(entry, 1, 2, 0, 1)
        values.append(entry)
        label = gtk.GtkLabel("View command:")
        label.show()
        table.attach(label, 0, 1, 1, 2)
        entry = gtk.GtkEntry()
        entry.set_text(view_command)
        entry.show()
        table.attach(entry, 1, 2, 1, 2)
        values.append(entry)
        table.show()
        frame.add(table)
        frame.show()
        dialog.vbox.pack_start(frame, gtk.TRUE, gtk.TRUE, 0)

        frame = gtk.GtkFrame("Thumbnails")
        table = gtk.GtkTable(2, 2, gtk.TRUE)
        label = gtk.GtkLabel("Thumbnail size:")
        label.show()
        table.attach(label, 0, 1, 0, 1)
        entry = gtk.GtkEntry()
        entry.set_text(thumb_size)
        entry.show()
        table.attach(entry, 1, 2, 0, 1)
        values.append(entry)
        label = gtk.GtkLabel("Thumbnail columns:")
        label.show()
        table.attach(label, 0, 1, 1, 2)
        adj = gtk.GtkAdjustment(thumb_cols, 1, 10, 1, 1, 1)
        entry = gtk.GtkSpinButton(adj, 1, 0)
        entry.show()
        table.attach(entry, 1, 2, 1, 2)
        values.append(entry)
        table.show()
        frame.add(table)
        frame.show()
        dialog.vbox.pack_start(frame, gtk.TRUE, gtk.TRUE, 0)

        button = gtk.GtkButton("OK")
        button.connect("clicked", self.set_options, values, dialog)
        button.show()
        dialog.action_area.pack_start(button, gtk.TRUE, gtk.TRUE, 0)
        button = gtk.GtkButton("Cancel")
        button.connect("clicked", self.close_dialog, dialog)
        button.show()
        dialog.action_area.pack_start(button, gtk.TRUE, gtk.TRUE, 0)
        dialog.set_policy(gtk.FALSE, gtk.FALSE, gtk.FALSE)
        dialog.show()

    def set_options(self, widget, values, dialog):
        global set_command, view_command, thumb_size, thumb_cols
        set_command = values[0].get_text()
        view_command = values[1].get_text()
        if thumb_size != values[2].get_text():
            thumb_size = values[2].get_text()
            # TODO: resize old thumbs
        if thumb_cols != values[3].get_value_as_int():
            thumb_cols = values[3].get_value_as_int()
            self.layout(0)
        dialog.destroy()

    def layout(self, i):
        global thumb_cols
        num_imgs = len(self.images)
        for i in range(i, num_imgs):
            self.table.remove(self.images[i])
            c = i % thumb_cols
            r = i / thumb_cols
            self.table.attach(self.images[i], c, c + 1, r, r + 1, 0, 0,\
                              self.padding, self.padding)
        cols = min(thumb_cols, num_imgs)
        rows = num_imgs / thumb_cols + (num_imgs % thumb_cols != 0)
        self.table.resize(rows, cols)

    def create_menu(self, widget, data):
        # sometimes the statusbar does not get cleared; do it manually
        self.clear_status(None, None)
        chooser = gtk.GtkFileSelection("Create background menu")
        chooser.set_transient_for(self.window)
        # center, regardless of where the parent is.
        # This is the best alternative, since IN_POS_CENTER_ON_PARENT does not
        # exists in GTK1
        chooser.set_position(gtk.WIN_POS_CENTER)
        # GTK1 has no support for multiple selections, so no need to set to
        # single selection
        chooser.ok_button.connect("clicked", self.create_menu0, chooser)
        chooser.cancel_button.connect("clicked", self.close_dialog, chooser)
        chooser.show()

    def create_menu0(self, widget, chooser):
        global set_command
        file = chooser.get_filename()
        f = open(file, "w")
        f.write("[submenu] (Backgrounds)\n")
        for i in self.images:
            f.write("  [exec] (" + i.description + ") {" + set_command + " " +\
                    i.filename + "}\n")
        f.close()
        chooser.destroy()

    def create_list(self, widget, data):
        # sometimes the statusbar does not get cleared; do it manually
        self.clear_status(None, None)
        chooser = gtk.GtkFileSelection("Create background list")
        chooser.set_transient_for(self.window)
        # center, regardless of where the parent is.
        # This is the best alternative, since IN_POS_CENTER_ON_PARENT does not
        # exists in GTK1
        chooser.set_position(gtk.WIN_POS_CENTER)
        # GTK1 has no support for multiple selections, so no need to set to
        # single selection
        chooser.ok_button.connect("clicked", self.create_list0, chooser)
        chooser.cancel_button.connect("clicked", self.close_dialog, chooser)
        chooser.show()

    def create_list0(self, widget, chooser):
        file = chooser.get_filename()
        f = open(file, "w")
        for i in self.images:
            f.write(i.filename + "\n")
        f.close()
        chooser.destroy()

    def random_background(self, widget, data):
        if self.images:
            img = choice(self.images)
            self.set(widget, img)

    def about(self, widget, data):
        global version, info_img
        # sometimes the statusbar does not get cleared; do it manually
        self.clear_status(None, None)
        text = "bbbm1 " + version + "\nWritten by Rob Spoor\n\n" +\
               "CopyRight 2004 Rob Spoor"
        dialog = gtk.GtkDialog()
        dialog.set_title("About")
        dialog.set_transient_for(self.window)
        # center, regardless of where the parent is.
        # This is the best alternative, since IN_POS_CENTER_ON_PARENT does not
        # exists in GTK1
        dialog.set_position(gtk.WIN_POS_CENTER)
        hbox = gtk.GtkHBox(gtk.FALSE, 0)
        gdk_pixmap, mask = gtk.create_pixmap_from_xpm_d(\
            self.window.get_window(),\
            self.window.get_style().bg[gtk.STATE_NORMAL], info_img)
        pixmap = gtk.GtkPixmap(gdk_pixmap, mask)
        pixmap.show()
        hbox.pack_start(pixmap, gtk.FALSE, gtk.FALSE, 0)
        label = gtk.GtkLabel(text)
        label.set_justify(gtk.JUSTIFY_LEFT)
        label.show()
        hbox.pack_start(label, gtk.FALSE, gtk.FALSE, 0)
        hbox.show()
        dialog.vbox.pack_start(hbox, gtk.TRUE, gtk.TRUE, 0)
        okbutton = gtk.GtkButton("OK")
        okbutton.connect("clicked", self.close_dialog, dialog)
        okbutton.show()
        dialog.action_area.pack_start(okbutton, gtk.TRUE, gtk.TRUE, 0)
        dialog.show()

    def set_img(self, widget, event, image):
        if event.type == GDK._2BUTTON_PRESS:
            self.set(widget, image)

    def popup(self, widget, event, image):
        # button 3 should be the right button
        if event.type == GDK.BUTTON_RELEASE and event.button == 3:
            popup = gtk.GtkMenu()
            menu_items = [
                ("Set", self.set), ("View", self.view), ("<sep>", None),
                ("Edit description", self.edit_descr),
                ("Delete", self.delete)
            ]
            for name, action in menu_items:
                if name == "<sep>":
                    item = gtk.GtkMenuItem()
                else:
                    item = gtk.GtkMenuItem(name)
                if action:
                    item.connect("activate", action, image)
                item.show()
                popup.append(item)
            popup.popup(None, None, None, event.button, event.time)

    def set(self, widget, image):
        global set_command
        os.system(set_command + " " + image.filename)

    def view(self, widget, image):
        global view_command
        os.system(view_command + " " + image.filename)

    def edit_descr(self, widget, image):
        # sometimes the statusbar does not get cleared; do it manually
        self.clear_status(None, None)
        dialog = gtk.GtkDialog()
        dialog.set_title("Edit description")
        dialog.set_transient_for(self.window)
        # center, regardless of where the parent is.
        # This is the best alternative, since IN_POS_CENTER_ON_PARENT does not
        # exists in GTK1
        dialog.set_position(gtk.WIN_POS_CENTER)
        frame = gtk.GtkFrame("Description")
        frame.show()
        table = gtk.GtkTable(2, 1, gtk.TRUE)
        table.show()
        frame.add(table)
        label = gtk.GtkLabel("Description:")
        label.show()
        table.attach(label, 0, 1, 0, 1)
        entry = gtk.GtkEntry()
        entry.set_text(image.description)
        entry.show()
        table.attach(entry, 0, 1, 1, 2)
        dialog.vbox.pack_start(frame, gtk.TRUE, gtk.TRUE, 0)
        button = gtk.GtkButton("OK")
        button.connect("clicked", self.set_descr, image, entry, dialog)
        button.show()
        dialog.action_area.pack_start(button, gtk.TRUE, gtk.TRUE, 0)
        button = gtk.GtkButton("Cancel")
        button.connect("clicked", self.close_dialog, dialog)
        button.show()
        dialog.action_area.pack_start(button, gtk.TRUE, gtk.TRUE, 0)
        dialog.show()

    def set_descr(self, widget, image, entry, dialog):
        image.description = entry.get_text()
        dialog.destroy()

    def delete(self, widget, image):
        i = self.images.index(image)
        self.images.remove(image)
        self.table.remove(image)
        if i == len(self.images):
            # just remove it, no need to call self.layout
            pass
        else:
            self.layout(i)

    def close_dialog(self, widget, dialog):
        dialog.destroy()

if __name__ == "__main__":
    try:
        opts, files = getopt.getopt(sys.argv[1:], "hv", ["help", "version"])
    except getopt.error, e:
        sys.stderr.write("bbbm1: " + str(e) + "\n")
        sys.stderr.write("Try `bbbm1 --help` for more information\n")
        sys.exit(1)
    for o in opts:
        if o[0] == "-h" or o[0] == "--help":
            print "Usage: bbbm1 [OPTIONS] [COLLECTION]"
            print "Opens the Blackbox background manager."
            print
            print "  -h, --help     Output this help and exit"
            print "  -v, --version  Output version information and exit"
            sys.exit(0)
        if o[0] == "-v" or o[0] == "--version":
            print "bbbm1", version
            print "Written by Rob Spoor"
            print
            print "CopyRight 2004 Rob Spoor"
            sys.exit(0)
    if not exists(homedir):
        os.mkdir(homedir)
    if not exists(config):
        conf = open(config, "w")
        conf.close()
        set_command, view_command = "bsetbg", "gqview"
        thumb_size, thumb_cols = "128x96", 4
        write_options()
    read_options()

    BBBM(files)
    gtk.mainloop()

